-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Lakat/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE lakat_staging (
  la_id SERIAL NOT NULL,
  la_branch_name TEXT NOT NULL,
  la_name TEXT NOT NULL,
  la_rev_id INT DEFAULT NULL,
  PRIMARY KEY(la_id)
);

CREATE UNIQUE INDEX la_branch_article_unique ON lakat_staging (la_branch_name, la_name);
