-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Lakat/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/lakat_staging (
  la_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  la_branch_name VARBINARY(255) NOT NULL,
  la_name VARBINARY(255) NOT NULL,
  UNIQUE INDEX la_branch_article_unique (la_branch_name, la_name),
  PRIMARY KEY(la_id)
) /*$wgDBTableOptions*/;
